### ISSUE TITLE
--daemon should be a command

### ISSUE THREAD

**Issue by michaeldg** [tanji/replication-manager#34]
I like the idea of the subcommands in mrm. Perhaps the --daemon switch in the monitor subcommand should be a separate command?

**Comment by tanji** [comment]
It's debatable. Monitor and Daemon do exactly the same thing in code, the only difference is that the termbox isn't started...

**Comment by michaeldg** [comment]
For the end user it's a completely different behaviour :)

**Comment by tanji** [comment]
I doubt that typing "monitor --daemon" or "daemon" makes a big difference :)

**Comment by michaeldg** [comment]
that is debatable - if you installed it and use --help, I would not guess to go to interactive mode if I want to start a daemon.

**Comment by tanji** [comment]
If other users think this is relevant I will implement it.

**Comment by sysdljr** [comment]
Hello  @tanji , 
I  advise to add daemon parameter too ,thank.
