### ISSUE TITLE
Mrm breaks if no transactions have been executed after a failover

### ISSUE THREAD

**Issue by michaeldg** [tanji/replication-manager#45]
If MRM does a failover but no transactions have been executed afterwards the next failover does not work.

Also it will not work if only transactions from old school slave has been executed in between the 2 failovers (see MDEV-10279). 

As this would not really happen in the wild I suggest adding a work-around: Please execute a bogus transaction _after_ the failover has succeeded.

**Comment by tanji** [comment]
Could not reproduce, please provide test case.

MDEV 10279 is known. Workaround is to use slave-pos.
