### ISSUE TITLE
one master and two slave failover question ?

### ISSUE THREAD

**Issue by sysdljr** [tanji/replication-manager#46]
Hi, 
    we use one master and two slave in replication-manager 0.6.4.
master: 172.28.14.114
slave:     172.28.14.118, 172.28.14.117

when we stop mysql service at 172.28.14.114,   Slave 172.28.14.117  elected as a new master, 
172.28.14.118 as slave of 172.28.14.117 and replication normal.
but ,when we start mysql service at 172.28.14.114,  io thread show error:
Got fatal error 1236 from master when reading data from binary log: 'Error: connecting slave requested to start from GTID 0-114-1775428, which is not in the master's binlog. Since the master's binlog contains GTIDs with higher sequence numbers, it probably means that the slave has diverged due to executing extra erroneous transactions'

 MariaDB Replication Monitor and Health Checker version 0.6.3  |  Mode: Auto Failover 

```
Master Host   Port                              Current GTID      Binlog Position  Strict Mode
```

  172.28.14.117   3306                             0-117-1790726        0-117-1790726          OFF

```
 Slave Host   Port  Binlog   Using GTID         Current GTID           Slave GTID   Replication Health  Delay  RO
```

  172.28.14.118   3306      ON    Slave_Pos        0-117-1790694        0-117-1790694        Behind master      1  ON
  172.28.14.114   3306      ON  Current_Pos        0-114-1775428        0-118-1648605   NOT OK, IO Stopped      0  ON

 Ctrl-Q to quit, Ctrl-S to switchover                                                             

 2016-06-24 22:49:07 INFO : Master switch on 172.28.14.117 complete
 2016-06-24 22:49:04 INFO : Change master on slave 172.28.14.118  
 2016-06-24 22:49:04 INFO : Switching other slaves to the new master  
 2016-06-24 22:49:04 INFO : Resetting slave on new master and set read/write mode on
 2016-06-24 22:49:03 INFO : Stopping slave thread on new master  
 2016-06-24 22:49:03 INFO : Switching master  
 2016-06-24 22:49:03 INFO : Slave 172.28.14.117 [0] has been elected as a new master
 2016-06-24 22:49:03 INFO : Electing a new master  
 2016-06-24 22:49:03 INFO : Starting master switch  
 2016-06-24 22:49:03 Declaring master as failed  
 2016-06-24 22:49:03 Master Failure detected! Retry 5/5  
 2016-06-24 22:49:02 Master Failure detected! Retry 4/5  
 2016-06-24 22:49:01 Master Failure detected! Retry 3/5  
 2016-06-24 22:49:00 Master Failure detected! Retry 2/5  
 2016-06-24 22:48:59 Master Failure detected! Retry 1/5

**Comment by sysdljr** [comment]
after we execute command  below,  replication manager show  172.28.14.114 normal.
 stop slave; change master to master_host='172.28.14.117',master_user='rep_user',master_password='xxxxxx', master_port=3306,master_use_gtid=slave_pos;
start slave;


 MariaDB Replication Monitor and Health Checker version 0.6.3  |  Mode: Auto Failover                                                        
                                                                                                                                             
    Master Host   Port                              Current GTID      Binlog Position  Strict Mode                                           
  172.28.14.117   3306                             0-117-1925332        0-117-1925332          OFF                                           
                                                                                                                                             
     Slave Host   Port  Binlog   Using GTID         Current GTID           Slave GTID   Replication Health  Delay  RO                        
  172.28.14.114   3306      ON    Slave_Pos        0-117-1824867        0-117-1824867        Behind master    819  ON                        
  172.28.14.118   3306      ON    Slave_Pos        0-117-1925332        0-117-1925332           Running OK      0  ON

**Comment by tanji** [comment]
Hi @sysdljr 
Master reintroduction is a complex science... And it's not guaranteed that it will work in all cases.
As you see above in your example, master has diverged. Probably because when you stopped it, it was still receving traffic.
In this case old master data is inconsistent and should be re-bootstrapped from a new master backup.

How did you stop your old master? mysql shutdown? kill mysql? power off? I'm interested to know how we could improve replication-manager to handle such cases.

**Comment by tanji** [comment]
What was the value of slave_pos before you execute CHANGE MASTER?

**Comment by sysdljr** [comment]
Thank you rapid reply.
yes ,you is correct.  when we stop mysql ,  running sysbench test.
sysbench --test=/usr/share/doc/sysbench/tests/db/oltp.lua --num-threads=4  --mysql-host=172.28.14.91 --mysql-port=4006 --mysql-user=myuser --mysql-password=mypwd --mysql-db=test --max-time=0 --max-requests=0  --report-interval=1 --oltp-tables-count=4 run
we  stop mysql ：  /etc/init.d/mysql stop

**Comment by tanji** [comment]
can you please test with 0.7.0-beta3?

**Comment by tanji** [comment]
Just a clarification, I see a port 4006. Are you using MaxScale?

**Comment by sysdljr** [comment]
show global variables like '%gtid%';

| Variable_name          | Value                      |
+------------------------+----------------------------+
| gtid_binlog_pos        | 0-118-1648609              |
| gtid_binlog_state      | 0-114-920937,0-118-1648609 |
| gtid_current_pos       | 0-118-1648609              |
| gtid_domain_id         | 0                          |
| gtid_ignore_duplicates | OFF                        |
| gtid_slave_pos         | 0-114-920937               |
| gtid_strict_mode       | OFF                        |
| wsrep_gtid_domain_id   | 0                          |
| wsrep_gtid_mode        | OFF                        |
+------------------------+-----

execute change master  ...  master_use_gtid=current_pos , slave show Got fatal error 1236 
execute change master  ...  master_use_gtid=slave_pos;  slave OK.

**Comment by sysdljr** [comment]
yes . we use maxscale 1.4.3

**Comment by sysdljr** [comment]
Thank you again.
we should test  0.7.0-beta3.

**Comment by svaroqui** [comment]
Hello sysdljr, 

This is expected from assync replication if the replication is delay   because of high load on the master. 

What can be done is to activate semisync and use parallel replication. use a big number of replication_threads on the slave something like may be 2 times the concurrency of sysbench   

Try similar settings 
thread_handling=pool-of-threads
extra-port=3307

# semisync 
plugin-load="semisync_master.so;semisync_slave.so"
rpl_semi_sync_master=ON
rpl_semi_sync_slave=ON
loose_rpl_semi_sync_master_enabled=ON
loose_rpl_semi_sync_slave_enabled=ON


slave-parallel-mode=optimistic
slave_domain_parallel_threads=%%ENV:CORES%% 

Can you please rebench this settings ( 10.1 needed)

**Comment by sysdljr** [comment]
svaroqui, Thank you too,  I will test  semisync

**Comment by tanji** [comment]
@sysjdir: in maxscale.cnf what is the value of monitor_interval ?

**Comment by sysdljr** [comment]
monitor_interval is default value:  10000

mysql monitor config:
[MySQL Monitor]
type=monitor
module=mysqlmon
servers=server1,server2,server3
user=myuser
passwd=mypwd
monitor_interval=10000
events=master_down
detect_replication_lag=true

we have not add monitor script in maxscale . if add monitro script , Is it the fromat at below ?
script=/usr/local/bin/replication-manager --user root:xxx --rpluser repluser:xxx --hosts $INITIATOR,$NODELIST --failover=force --interactive=false

**Comment by tanji** [comment]
@sysdljr so, your old master diverges because MaxScale needs max. 10 seconds to recognize that the topology has changed. In the meantime it continues sending writes to that server. You have two solutions:
1) Change the monitor_interval to a value that is possibly lower than the failover time. e.g. monitor_interval=500 (this value generally worked for me)
2) Don't use MRM as standalone and configure maxscale to start MRM to process the failover. In this case, set the following variables in maxscale.cnf:

### For 0.6
script=/usr/local/bin/replication-manager --user root:xxx --rpluser repluser:xxx --hosts $INITIATOR,$NODELIST --failover=force --interactive=false

### For 0.7
script=/usr/local/bin/replication-manager failover --user root:xxx --rpluser repluser:xxx --hosts $INITIATOR,$NODELIST --interactive=false

**Comment by sysdljr** [comment]
@tanji , thank you.

The time,  I have not  use MRM 0.6 as a standalone server.
I modify maxscale.cnf ,  when stop mysql at master (172.28.14.114),  not slave elected as a new master.  I can't confirm where have problem ?   please help ,thanks.

[MySQL Monitor]
type=monitor
module=mysqlmon
servers=server1,server2,server3
user=myuser
passwd=mypwd
monitor_interval=100
script=/usr/local/bin/replication-manager --user root:xxx --rpluser repluser:xxx --hosts $INITIATOR,$NODELIST --failover=force --interactive=false
events=master_down
detect_replication_lag=true


maxscale log  contents : 
2016-06-25 20:02:38   error  : Monitor was unable to connect to server 172.28.14.114:3306 : "Can't connect to MySQL server on '172.28.14.114' (107)"
2016-06-25 20:02:38   notice : Server 172.28.14.114:3306 lost the master status.
2016-06-25 20:02:38   notice : Server changed state: server1[172.28.14.114:3306]: master_down
2016-06-25 20:02:38   notice : Server changed state: server2[172.28.14.118:3306]: lost_slave
2016-06-25 20:02:38   notice : Server changed state: server3[172.28.14.117:3306]: lost_slave
2016-06-25 20:02:38   error  : No Master can be determined. Last known was 172.28.14.114:3306

MaxScale> show servers
Server 0x1b2a370 (server1)
        Server:                              172.28.14.114
        Status:                              Down
        Protocol:                    MySQLBackend
        Port:                                3306
        Server Version:                 10.1.14-MariaDB
        Node Id:                     114
        Master Id:                   -1
        Slave Ids:                   
        Repl Depth:                  0
        Last Repl Heartbeat:    1466856147
        Number of connections:               4
        Current no. of conns:                0
        Current no. of operations:   0
        Persistent pool size:            0
        Persistent measured pool size:   0
        Persistent max size achieved:    0
        Persistent pool size limit:      10
        Persistent max time (secs):          0
Server 0x1b2a290 (server2)
        Server:                              172.28.14.118
        Status:                              Running
        Protocol:                    MySQLBackend
        Port:                                3306
        Server Version:                 10.1.14-MariaDB
        Node Id:                     118
        Master Id:                   -1
        Slave Ids:                   
        Repl Depth:                  -1
        Last Repl Heartbeat:    1466856137
        Number of connections:               4
        Current no. of conns:                0
        Current no. of operations:   0
Server 0x1b2a070 (server3)
        Server:                              172.28.14.117
        Status:                              Running
        Protocol:                    MySQLBackend
        Port:                                3306
        Server Version:                 10.1.14-MariaDB
        Node Id:                     117
        Master Id:                   -1
        Slave Ids:                   
        Repl Depth:                  -1
        Last Repl Heartbeat:    1466856137
        Number of connections:               4
        Current no. of conns:                0
        Current no. of operations:   0

**Comment by sysdljr** [comment]
if use mrm0.7 script in maxscale.  when stop master ,  one slave elected as a new master, other slave change master to new master normal..
script=/usr/local/bin/replication-manager failover --user root:xxx --rpluser repluser:xxx --hosts $INITIATOR,$NODELIST --interactive=false

maxscale log contents:
2016-06-25 20:52:37   error  : Monitor was unable to connect to server 172.28.14.114:3306 : "Can't connect to MySQL server on '172.28.14.114'
 (107)"
2016-06-25 20:52:37   notice : Server 172.28.14.114:3306 lost the master status.
2016-06-25 20:52:37   notice : Server changed state: server1[172.28.14.114:3306]: master_down
2016-06-25 20:52:37   notice : Server changed state: server2[172.28.14.118:3306]: lost_slave
2016-06-25 20:52:37   notice : Server changed state: server3[172.28.14.117:3306]: lost_slave
2016-06-25 20:52:37   error  : No Master can be determined. Last known was 172.28.14.114:3306
2016-06-25 20:52:48   notice : Server changed state: server2[172.28.14.118:3306]: new_master
2016-06-25 20:52:48   notice : Server changed state: server3[172.28.14.117:3306]: new_slave
2016-06-25 20:52:48   notice : A Master Server is now available: 172.28.14.118:3306

After old master start , maxscale log:  
2016-06-25 20:57:23   notice : Server changed state: server1[172.28.14.114:3306]: server_up

**Comment by tanji** [comment]
Yes that behavior is normal. If you use MRM with MaxScale, failover is one shot, so server1 cannot be reintroduced automatically. You have to restart it yourself.

For the 0.6 I have no idea. It would help if you add the options: --verbose --logfile=/tmp/mrm.log to the script and send the mrm.log file.

**Comment by sysdljr** [comment]
@tanji, Thank you very much.
Just now, I use MRM 0.6 and add verbose and logfile options in MaxScale, 
script=/usr/local/bin/replication-manager --user root:xxx --rpluser repluser:xxx --hosts $INITIATOR,$NODELIST --failover=force --interactive=false --verbose --logfile=/tmp/mrm.log 
But ,After stop master, two slaves show status: Running, no have slave elected as a new master,  and /tmp/mrm.log is empty.

In addition, when master down, If execute MRM 0.6 command line at below ,  failover OK
/usr/local/bin/replication-manager --user=root:123456 --rpluser=rep_user:123456 --hosts="172.28.14.114,172.28.14.117,172.28.14.118" --failover=force --interactive=false --verbose --logfile=/tmp/mrm.log 
                      
2016/06/27 22:24:50 DEBUG: Creating new server: 172.28.14.114
2016/06/27 22:24:50 ERROR: dial tcp 172.28.14.114:3306: getsockopt: connection refused
2016/06/27 22:24:50 INFO : Server 172.28.14.114 is dead.
2016/06/27 22:24:50 DEBUG: Creating new server: 172.28.14.117
2016/06/27 22:24:50 DEBUG: Checking if server 172.28.14.117 is slave
2016/06/27 22:24:50 DEBUG: Server 172.28.14.117 is configured as a slave
2016/06/27 22:24:50 DEBUG: Creating new server: 172.28.14.118
2016/06/27 22:24:50 DEBUG: Checking if server 172.28.14.118 is slave
2016/06/27 22:24:50 DEBUG: Server 172.28.14.118 is configured as a slave
2016/06/27 22:24:50 DEBUG: Server 172.28.14.114 was autodetected as a master
2016/06/27 22:24:50 DEBUG: Checking if server 172.28.14.117 is a slave of server 172.28.14.114
2016/06/27 22:24:50 DEBUG: Checking if server 172.28.14.118 is a slave of server 172.28.14.114
2016/06/27 22:24:50 INFO : Starting master switch
2016/06/27 22:24:50 INFO : Electing a new master
2016/06/27 22:24:50 DEBUG: Processing 2 candidates
2016/06/27 22:24:50 INFO : Slave 172.28.14.117 [0] has been elected as a new master
2016/06/27 22:24:50 INFO : Switching master
2016/06/27 22:24:50 INFO : Stopping slave thread on new master
2016/06/27 22:24:50 INFO : Resetting slave on new master and set read/write mode on
2016/06/27 22:24:50 INFO : Switching other slaves to the new master
2016/06/27 22:24:50 INFO : Change master on slave 172.28.14.118
2016/06/27 22:24:51 INFO : Master switch on 172.28.14.117 complete

/tmp/mr.log:
2016/06/27 22:24:50 INFO : Starting master switch
2016/06/27 22:24:50 INFO : Electing a new master
2016/06/27 22:24:50 DEBUG: Processing 2 candidates
2016/06/27 22:24:50 INFO : Slave 172.28.14.117 [0] has been elected as a new master
2016/06/27 22:24:50 INFO : Switching master
2016/06/27 22:24:50 INFO : Stopping slave thread on new master
2016/06/27 22:24:50 INFO : Resetting slave on new master and set read/write mode on
2016/06/27 22:24:50 INFO : Switching other slaves to the new master
2016/06/27 22:24:50 INFO : Change master on slave 172.28.14.118
2016/06/27 22:24:51 INFO : Master switch on 172.28.14.117 complete
